/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghibli.interfaces;

import ghibli.Cliente;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author Gabrielly
 */
public class CadastroFrame extends javax.swing.JFrame {

    private JTextField nomeField, emailField, telefoneField, cpfField;
    private JPasswordField senhaField;
    private JButton cadastrarButton, voltarButton;
    private ArrayList<Cliente> listaClientes;
    
    public CadastroFrame(ArrayList<Cliente> listaClientes) {
        this.listaClientes = listaClientes;
        
        setTitle("Cadastro - Ghibli Store");
        setSize(350, 300);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);
        
        JLabel nomeLabel = new JLabel("Nome:");
        nomeLabel.setBounds(30, 20, 80, 25);
        add(nomeLabel);
        
        nomeField = new JTextField();
        nomeField.setBounds(110, 20, 180, 25);
        add(nomeField);
        
        JLabel emailLabel = new JLabel("Email:");
        emailLabel.setBounds(30, 60, 80, 25);
        add(emailLabel);
        
        emailField = new JTextField();
        emailField.setBounds(110, 60, 180, 25);
        add(emailField);
        
        JLabel telefoneLabel = new JLabel("Telefone:");
        telefoneLabel.setBounds(30, 100, 80, 25);
        add(telefoneLabel);
        
        telefoneField = new JTextField();
        telefoneField.setBounds(110, 100, 180, 25);
        add(telefoneField);
        
        JLabel cpfLabel = new JLabel("CPF:");
        cpfLabel.setBounds(30, 140, 80, 25);
        add(cpfLabel);
        
        cpfField = new JTextField();
        cpfField.setBounds(110, 140, 180, 25);
        add(cpfField);
        
        JLabel senhaLabel = new JLabel("Senha:");
        senhaLabel.setBounds(30, 180, 80, 25);
        add(senhaLabel);
        
        senhaField = new JPasswordField();
        senhaField.setBounds(110, 180, 180, 25);
        add(senhaField);
        
        cadastrarButton = new JButton("Cadastrar");
        cadastrarButton.setBounds(30, 220, 120, 25);
        add(cadastrarButton);
        
        voltarButton = new JButton("Voltar");
        voltarButton.setBounds(170, 220, 120, 25);
        add(voltarButton);
        
        cadastrarButton.addActionListener(e -> {
            String nome = nomeField.getText();
            String email = emailField.getText();
            String telefone = telefoneField.getText();
            String cpf = cpfField.getText();
            String senha = new String(senhaField.getPassword());
            
            if(nome.isEmpty() || email.isEmpty() || telefone.isEmpty() || cpf.isEmpty() || senha.isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
                return;
            }
            
            Cliente novoCliente = new Cliente(nome, email, telefone, cpf, senha);
            novoCliente.criarConta();
            listaClientes.add(novoCliente);
            
            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
            new LoginFrame(listaClientes).setVisible(true);
            dispose();
        });
        
        voltarButton.addActionListener(e -> {
            new LoginFrame(listaClientes).setVisible(true);
            dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ArrayList<Cliente> listaClientes = new ArrayList<>();
                new CadastroFrame(listaClientes).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
