/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ghibli.interfaces;

import ghibli.Cliente;
import ghibli.Filme;
import ghibli.Item;

import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;

/**
 *
 * @author Gabrielly
 */
public class CatalogoFrame extends javax.swing.JFrame {

    private JList<String> listaFilmes;
    private JButton adicionarCarrinhoBtn, verCarrinhoBtn;
    private ArrayList<Filme> filmesDisponiveis = new ArrayList<>();
    private ArrayList<Item> carrinho = new ArrayList<>();
    private Cliente cliente;
    
    public CatalogoFrame(Cliente cliente) {
        this.cliente = cliente;
        
        setTitle("Catálogo de Filmes - Ghibli Store");
        setSize(400, 400);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLayout(null);

        // exemplo
        filmesDisponiveis.add(new Filme("A Viagem de Chihiro", "2001", "Fantasia", "Hayao Miyazaki", "Garota entra em mundo mágico."));
        filmesDisponiveis.add(new Filme("Meu Amigo Totoro", "1988", "Animação", "Hayao Miyazaki", "Duas irmãs conhecem espírito da floresta."));

        String[] titulos = filmesDisponiveis.stream().map(Filme::getTitulo).toArray(String[]::new);
        listaFilmes = new JList<>(titulos);
        JScrollPane scrollPane = new JScrollPane(listaFilmes);
        scrollPane.setBounds(30, 30, 320, 200);
        add(scrollPane);

        adicionarCarrinhoBtn = new JButton("Adicionar ao Carrinho");
        adicionarCarrinhoBtn.setBounds(30, 250, 160, 30);
        add(adicionarCarrinhoBtn);

        verCarrinhoBtn = new JButton("Ver Carrinho");
        verCarrinhoBtn.setBounds(200, 250, 150, 30);
        add(verCarrinhoBtn);

        adicionarCarrinhoBtn.addActionListener(e -> {
            int idx = listaFilmes.getSelectedIndex();
            if (idx >= 0) {
                Filme filmeSelecionado = filmesDisponiveis.get(idx);
                Item novoItem = new Item("SER" + (carrinho.size() + 1), "08/06/2025", filmeSelecionado);
                novoItem.adicionarCarrinho();
                carrinho.add(novoItem);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um filme.");
            }
        });

        verCarrinhoBtn.addActionListener(e -> {
            new CarrinhoFrame(cliente, carrinho).setVisible(true);
            dispose();
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CatalogoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente cliente = new Cliente("Antônia", "antonia@gmail.com", "12345678901", "a", "senha123");
                new CatalogoFrame(cliente).setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
